# Aula 07 - Manipulação de Strings com Python

> Uma variável primaria de texto é chamada de char ou caractér possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variáveis compostas no caso da maioria das linguagens chamadas de strings. Vamos ver como se aplica. 

In [182]:
frase = "boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

boa tarde a todos
boa tarde


In [183]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [184]:
print(frase.count(' '))
print(saudacao.count(' '))

3
1


In [185]:
print(len(frase))
print(len(saudacao))

17
9


In [186]:
frase = frase.replace('a todos','galerinha!')
print(frase)
saudacao = saudacao.replace('tarde', 'noite')
print(saudacao)

boa tarde galerinha!
boa noite


In [187]:
frase = [i for i in frase]
print(frase)

['b', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [188]:
for x in frase:
    print(x)

b
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício 1

> Crie um código para a seguinte frase: "Sabia que o sabiá sabia assobiar", reparticionado por espaços, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [189]:
sabia = "Sabia que o sabiá sabia assobiar"
sabia = sabia.replace(' ', '    |    ')
print(sabia)

Sabia    |    que    |    o    |    sabiá    |    sabia    |    assobiar


In [190]:
sabia = "Sabia que o sabiá sabia assobiar"
palavras = sabia.split()

for x in palavras:
    print(x)

Sabia
que
o
sabiá
sabia
assobiar


### Correção

In [191]:
frase = "Sabia que o sabiá sabia assobiar"

palavras = frase.split()

for i in range(max(len(x) for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end = ' ')

    print()

S q o s s a 
a u   a a s 
b e   b b s 
i     i i o 
a     á a b 
          i 
          a 
          r 


In [206]:
for i in range(max (len (x) for x in palavras)):
    print('   '.join(x[i] if i<len(x) else ' ' for x in palavras))

S   q   o   s   s   a
a   u       a   a   s
b   e       b   b   s
i           i   i   o
a           á   a   b
                    i
                    a
                    r


# Introdução a Numpy

> Numpy é uma biblioteca python para desenvolvimento de matrizes. tem por objetivos facilitar na criação de algoritmos matemáticos para solucionar paradgimas avançados em relação a arrays. 

In [193]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [194]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [195]:
b = np.array([(1,2,3), (4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


> Para demostrar '1'

In [196]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


> Para demostrar valores binários

In [197]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


> Para demostrar o maior valor

In [198]:
print(a.max())
print(b.max())
print(c.max())

3
6
1.0


> Para demostrar o menor valor

In [199]:
print(a.min())
print(b.min())
print(c.min())


1
1
1.0


> Para calcular soma

In [200]:
print(a.sum())
print(b.sum())
print(c.sum())

6
21
9.0


> Para calcular média

In [201]:
print(a.mean())
print(b.mean())
print(c.mean())

2.0
3.5
1.0


> Para desvio padrão

In [202]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))

0.82
1.71
0.0


## Exercício 2

> Crie uma matriz chamada contar com os números de 0 até 9. Ao final crie uma contagem, média e desvio padrão dessa matriz. Para adicionar de 0 a 9 utilize um for e depois atribua à matriz.

In [203]:
contar = np.array([i for i in range(10)])
print(contar)
print(contar.mean())
print(round(contar.std(),2))

[0 1 2 3 4 5 6 7 8 9]
4.5
2.87
